/*
Programming Project 9 in Chapter 5 asked you to write a program that determines which of
two dates comes earlier on the calendar. Generalize the program so that the user may enter
any number of dates. The user will enter 0/0/0 to indicate that no more dates will be entered:
Enter a date (mm/dd/yy): 3/6/08
Enter a date (mm/dd/yy): 5/17/07
Enter a date (mm/dd/yy): 6/3/07
Enter a date (mm/dd/yy): 0/0/0
5/17/07 is the earliest date
*/

#include <stdio.h>

int main(void) {
    int nMonth, nDay, nYear;
    int nMinMonth, nMinDay, nMinYear;
    int first = 1;

    while (1) {
        printf("Enter a date (mm/dd/yy): ");
        scanf("%d/%d/%d", &nMonth, &nDay, &nYear);

        if (nMonth == 0 && nDay == 0 && nYear == 0)
            break;

        
        if (first) {
            nMinMonth = nMonth;
            nMinDay = nDay;
            nMinYear = nYear;
            first = 0;
        } else if ((nYear < nMinYear) ||
                   (nYear == nMinYear && nMonth < nMinMonth) ||
                   (nYear == nMinYear && nMonth == nMinMonth && nDay < nMinDay)) {
            nMinMonth = nMonth;
            nMinDay = nDay;
            nMinYear = nYear;
        }
    }

    printf("%d/%d/%d is the earliest date\n", nMinMonth, nMinDay, nMinYear);
    return 0;
}

/* This is code that generated by ChatGPT. This part is little bit tricky as it dealing with 
 * some variable error. Before any operation particularly the one like selection statement, 
 * the variables must be assigned to avoid variables pick any random garbages from stack memory.
 * On my first try, I am using Do While loop to enter and compare the day, month and year, but my 
 * mistake is I didn't assign the value of nDay, nMonth, and nYear. 
 */


